CREATE TABLE Teams (
	Id INT NOT NULL,
	Name VARCHAR(100) NOT NULL,
	ShortName VARCHAR(100) NULL,
	Tla VARCHAR(20) NULL ,
	Crest VARCHAR(200) NULL,
	Address VARCHAR(200) NULL,
	Website VARCHAR(200) NULL,
	Founded INT NULL,
	ClubColors VARCHAR(100) NULL,
	Venue VARCHAR(150) NULL,
	LastUpdated TIMESTAMP NULL,
	PRIMARY KEY(Id)
)